[log]
path = "logs"
format = "log_%(date)s-%(time)s.txt"
level = 1
enabled = false

[net]
tickrate = 30
port = 1213
bindto = "::,0.0.0.0"

[status]
enabled = true

[game]
hostname = "[US West] SimpleStation14"
maxplayers = 16
type = 1
welcomemsg = "Welcome to the server!"
lobbyenabled = true
lobbyduration = 140
role_timers = false

[whitelist]
min_players = 8

[suspicion]
min_players = 3
[traitor]
min_players = 2
[zombie]
min_players = 2
[pirates]
min_players = 1

[rules]
rules.time = 30
rules.exempt_local = false

[mapping]
autosave_interval = 60

[vote]
map_enabled = true

[atmos]
space_wind = true

[shuttle]
emergency_early_launch_allowed = true

[ic]
restricted_names = false
flavor_text = true

[ooc]
enable_during_round = true

[console]
loginlocal = true

[hub]
advertise = false
tags = "sandbox"
server_url = "ss14://ss14.simplemodbot.tk"

[auth]
# 0 = Optional, 1 = Required, 2 = Disabled
mode = 1
allowlocal = true
